#!/bin/sh

[ -z "$MAIL_RECIPIENT" ] && echo "MAIL_RECIPIENT is not set, exiting" && exit 1
[ -z "$MAIL_SENDER" ] && echo "MAIL_SENDER is not set, exiting" && exit 1
[ -z "$MAIL_SUBJECT" ] && echo "MAIL_SUBJECT is not set, exiting" && exit 1
[ -z "$MAIL_MESSAGE" ] && echo "MAIL_MESSAGE is not set, exiting" && exit 1
[ -z "$MAIL_SERVER" ] && echo "MAIL_SERVER is not set, exiting" && exit 1

sendemail -f $MAIL_SENDER -t $MAIL_RECIPIENT -u "$MAIL_SUBJECT" -m "$MAIL_MESSAGE" -s $MAIL_SERVER
